/**
 * @overview This file contains the ValidationError class.
 * Error subclasses are necessary to normalize the responses across different microservices
 */

//used to assign an error type
import {ValidationError} from 'express-validator';

/**
 * @class RequestValidationError
 * @description extends the base class Error, and is used to normalize the error response
 * for user input validation errors.
 */
export class RequestValidationError extends Error {

    /**
     * @constructor
     * @param {ValidationError[]} errors An array of errors generated by the express-validator middleware
     */
    constructor(public errors: ValidationError[]){
        super();

        //Only because we are extending a built in class
        //Ensures that objects created by RequestValidationError gets
        //the Error object in it's prototype chain
        Object.setPrototypeOf(this, RequestValidationError.prototype);

    }
}
