/**
 * @overview This file contains an index for all available routes.
 *
 */

//imports
import express,{Router} from 'express';
import currentuserRouter from './auth/routes/currentuser.router';
import signinRouter from './auth/routes/sign-in.router'
import signoutRouter from './auth/routes/sign-out.router'
import signupRouter from './auth/routes/sign-up.router'
import {errorHandler} from "../../middleware/error-handler.middleware";


//Creating a router object
const indexRouter:Router = express.Router();

//Setting up user routes.
//NOTE: errorHandler is a middleware function (not a router) that handles any errors generated by any of the routes
//IndexRouter automatically chooses the correct router, based on the URL provided
indexRouter.use('/user', [currentuserRouter,signupRouter,signinRouter,signoutRouter, errorHandler]);

//exports
export = indexRouter;
