/**
 * @overview This file contains error handler middleware
 */

//import statements
import {NextFunction, Request,Response} from "express";
import {RequestValidationError} from "../errors/request-validation.error";
import {DatabaseConnectionError} from "../errors/database-connection.error";

/**
 * @function errorHandler
 * @description This function handles errors generated by any of the route handlers
 * and ensures that all final error messages are normalized (have the same structure)
 * @param {Error | RequestValidationError | DatabaseConnectionError} err The error message thrown by the Error object
 * @param {Request} req The request object
 * @param {Response} res The response object
 * @param {NextFunction} next Function to be called when all is done.
 * @return {Response} The normalized error message with the structure: {errors:[{message:err.message}]}
 */
export const errorHandler = (
    err: Error,
    req: Request,
    res: Response,
    next: NextFunction
) => {
    //checks if error is a RequestValidationError and handles the error accordingly
    if(err instanceof RequestValidationError){
        //contains an array of errors generated by the express-validator middleware
        //formats the errors into the desired format
        //NOTE: the field property is optional and won't be present on all error messages
        const formattedErrors = err.errors.map(error=>{
            return {message: error.msg,field:error.param}
        });
        return res.status(400).send({errors:formattedErrors})
    }

    //checks if error is a DatabaseConnectionError and handles the error accordingly
    if(err instanceof DatabaseConnectionError){
        return res.status(500).send({errors:[
                {message:err.reason} //NOTE: there is no field property on DatabaseConnectionErrors
            ]})
    }

    //Any other type of error
    res.status(400).send({errors:[
            {message:"Something went wrong"}
    ]})

}
