/**
 * @overview This file contains error handler middleware
 */

//import statements
import {NextFunction, Request,Response} from "express";
import {CustomError} from "../errors/custom.error";


/**
 * @function errorHandler
 * @description This function handles errors generated by any of the route handlers
 * and ensures that all final error messages are normalized (have the same structure)
 * @param {Error | RequestValidationError | DatabaseConnectionError} err The error message thrown by the Error object
 * @param {Request} req The request object
 * @param {Response} res The response object
 * @param {NextFunction} next Function to be called when all is done.
 * @return {Response} The normalized error message with the structure: {errors:[{message:err.message}]}
 */
export const errorHandler = (
    err: Error,
    req: Request,
    res: Response,
    next: NextFunction
) => {
    //checks if error is an instance of custom error and handles the error accordingly

    if(err instanceof CustomError ){
        return res.status(err.statusCode).send({errors:err.serializeErrors()})
    }

    //Any other type of error
    res.status(400).send({errors:[
            {message:"Something went wrong"}
    ]})

}
